FROM docker-registry.default.svc:5000/jupyterhubul/s2i-minimal-notebook-s3:3.6

USER root

COPY . /tmp/src

RUN rm -rf /tmp/src/.git* && \
    chown -R 1001 /tmp/src && \
    chgrp -R 0 /tmp/src && \
    chmod -R g+w /tmp/src && \
    rm -rf /tmp/scripts && \
    mv /tmp/src/.s2i/bin /tmp/scripts && \
    yum install -y epel-release && \
    rpm -v --import http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro && \
    rpm -Uvh --force http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm  && \
    yum install -y ffmpeg ffmpeg-devel && \
    rpm -Uvh --force http://rpmfind.net/linux/centos/7.6.1810/os/x86_64/Packages/libXaw-1.0.13-4.el7.i686.rpm  && \
    rpm -Uvh --force https://rpmfind.net/linux/centos/7.6.1810/os/x86_64/Packages/libpng-1.5.13-7.el7_2.x86_64.rpm && \
    rpm -Uvh --force https://rpmfind.net/linux/centos/7.6.1810/os/x86_64/Packages/gd-2.0.35-26.el7.i686.rpm
    rpm -Uvh --force http://rpmfind.net/linux/centos/7.6.1810/os/x86_64/Packages/graphviz-2.30.1-21.el7.x86_64.rpm

ENV XDG_CACHE_HOME=/opt/app-root/src/.cache

USER 1001

RUN /tmp/scripts/assemble

CMD [ "/opt/app-root/builder/run" ]
